/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.abdownloadmanager.desktop

import com.abdownloadmanager.UpdateManager
import com.abdownloadmanager.desktop.di.Di
import com.abdownloadmanager.desktop.repository.AppRepository
import com.abdownloadmanager.desktop.ui.Ui
import com.abdownloadmanager.desktop.utils.*
import com.abdownloadmanager.desktop.utils.renderapi.CustomRenderApi
import com.abdownloadmanager.desktop.utils.singleInstance.AnotherInstanceIsRunning
import com.abdownloadmanager.desktop.utils.singleInstance.MutableSingleInstanceServerHandler
import com.abdownloadmanager.desktop.utils.singleInstance.SingleInstanceUtil
import com.abdownloadmanager.integration.Integration
import com.abdownloadmanager.shared.util.DownloadSystem
import com.abdownloadmanager.shared.util.appinfo.PreviousVersion
import com.abdownloadmanager.shared.util.keepawake.KeepAwakeManager
import ir.amirab.util.logger.AppLogger
import ir.amirab.util.logger.appLogger
import ir.amirab.util.writeText
import kotlinx.coroutines.runBlocking
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import kotlin.system.exitProcess

class App : AutoCloseable,
    KoinComponent {
    private val downloadSystem: DownloadSystem by inject()
    private val appRepository: AppRepository by inject()
    private val integration: Integration by inject()
    private val previousVersion: PreviousVersion by inject()
    private val updateManager: UpdateManager by inject()
    private val keepAwakeManager: KeepAwakeManager by inject()
    private val customRenderApi: CustomRenderApi by inject()

    //TODO Setup Native Messaging Feature
    //private val browserNativeMessaging: NativeMessaging by inject()
    fun start(
        appArguments: AppArguments,
        singleInstanceServerHandler: MutableSingleInstanceServerHandler,
        globalAppExceptionHandler: GlobalAppExceptionHandler,
    ) {
        try {
            runBlocking {
                //make sure to not get any dependency until boot the DI Container
                Di.boot()
                // it's better to organize these list of boot functions in a separate class

                // boot configs from the storage so download manager can use them on boot!
                customRenderApi.boot()
                appRepository.boot()
                integration.boot()
                downloadSystem.boot()
                previousVersion.boot()
                keepAwakeManager.boot()
                //TODO Setup Native Messaging Feature
                //waiting for compose kmp to add multi launcher to nativeDistributions,the PR is already exists but not merger
                //or maybe I should use a custom solution
                //browserNativeMessaging.boot()
                SingleInstanceServerInitializer.boot(singleInstanceServerHandler)
                Ui.boot(appArguments, globalAppExceptionHandler)
            }
        } catch (e: Exception) {
            globalAppExceptionHandler.onProcessIsUseless()
            throw e
        }
    }

    override fun close() {
        //nothing yet!
    }
}


fun main(args: Array<String>) {
    try {
        AppArguments.init(args)
        AppProperties.boot()
        val appArguments = AppArguments.get()
        // TODO: Remove forced logging after debugging TEMP/TitleBarDirection issues
        AppLogger.init(
            writeToConsole = true,
            logFilePath = AppInfo.definedPaths.logDir,
        )
        // Fix: Set JNA temp directory to app's data dir to avoid issues with RamDisk/TEMP
        // JNA needs to extract native DLL (jnidispatch.dll) to a writable temp directory
        val jnaTmpDir = AppInfo.definedPaths.systemDir.resolve("jna_tmp").toFile()
        jnaTmpDir.mkdirs()
        System.setProperty("jna.tmpdir", jnaTmpDir.absolutePath)
        appLogger.i { "DIAGNOSTIC: Set jna.tmpdir = ${jnaTmpDir.absolutePath}" }
        // Diagnostic: print TEMP-related info at startup
        appLogger.i { "=== DIAGNOSTIC: Environment Variables ===" }
        appLogger.i { "java.io.tmpdir = ${System.getProperty("java.io.tmpdir")}" }
        appLogger.i { "TMP env = ${System.getenv("TMP")}" }
        appLogger.i { "TEMP env = ${System.getenv("TEMP")}" }
        appLogger.i { "USERPROFILE env = ${System.getenv("USERPROFILE")}" }
        appLogger.i { "dataDir = ${AppInfo.dataDir}" }
        appLogger.i { "logDir = ${AppInfo.definedPaths.logDir}" }
        // Check canWrite on java.io.tmpdir
        val tmpDir = java.io.File(System.getProperty("java.io.tmpdir"))
        appLogger.i { "DIAGNOSTIC: File(tmpdir).exists() = ${tmpDir.exists()}" }
        appLogger.i { "DIAGNOSTIC: File(tmpdir).isDirectory() = ${tmpDir.isDirectory()}" }
        appLogger.i { "DIAGNOSTIC: File(tmpdir).canWrite() = ${tmpDir.canWrite()}" }
        appLogger.i { "DIAGNOSTIC: File(tmpdir).canRead() = ${tmpDir.canRead()}" }
        appLogger.i { "DIAGNOSTIC: File(tmpdir).canExecute() = ${tmpDir.canExecute()}" }
        appLogger.i { "=== END DIAGNOSTIC ===" }
        if (appArguments.version) {
            dispatchVersionAndExit()
        }
        val singleInstance = SingleInstanceUtil(AppInfo.definedPaths.configDir)
        if (appArguments.exit) {
            exitExistingProcessAndExit(singleInstance)
        }
        if (appArguments.startIfNotStarted && !AppInfo.isInIDE()) {
            startAndWaitForRunIfNotRunning(singleInstance)
        }
        if (appArguments.getIntegrationPort) {
            dispatchIntegrationPortAndExit(singleInstance)
        }
        //going to start main app
        defaultApp(
            singleInstance = singleInstance,
            appArguments = appArguments,
        )

    } catch (e: Throwable) {
        appLogger.e(throwable = e) { "Fail to start the ${AppInfo.displayName} app because:" }
        System.err.println("Fail to start the ${AppInfo.displayName} app because:")
        e.printStackTrace()
        AppInfo.definedPaths.crashLogFile.writeText(e.stackTraceToString())
        exitProcess(-1)
    }
}

private fun startAppInAnotherProcess() {
    val exeFile = requireNotNull(AppInfo.exeFile)
    val cmd = listOf(
        exeFile,
        AppArguments.Args.BACKGROUND
    ).joinToString(" ").also {
//        println("executing $it")
    }
    Runtime.getRuntime().exec(cmd)
}

private fun dispatchVersionAndExit(): Nothing {
    print(AppInfo.version)
    exitProcess(0)
}

private fun exitExistingProcessAndExit(singleInstance: SingleInstanceUtil): Nothing {
    singleInstance.sendToInstance(Commands.exit)
    exitProcess(0)
}

private fun dispatchIntegrationPortAndExit(singleInstance: SingleInstanceUtil): Nothing {
    val port =
        singleInstance.sendToInstance(Commands.getIntegrationPort)
            .orElse { IntegrationPortBroadcaster.INTEGRATION_UNKNOWN }
    print(port)
    exitProcess(0)
}

private fun startAndWaitForRunIfNotRunning(
    singleInstance: SingleInstanceUtil,
    howMuchWait: Long = 10_000,
    initialDelay: Long = 0,
    eachTimeDelay: Long = 500L,
) {
    val deadLine = System.currentTimeMillis() + howMuchWait
    if (initialDelay > 0) {
        Thread.sleep(initialDelay)
    }
    var firstLoop = true
    while (true) {
        val isReady: Boolean = singleInstance
            .sendToInstance(Commands.isReady)
            .orElse {
//                println("or else $it")
                false
            }
//        println("isReady: $isReady")
        if (isReady) {
            return
        }
        if (firstLoop) {
            startAppInAnotherProcess()
//            println("send start signal")
        }
        if (System.currentTimeMillis() >= deadLine) {
//            println("dead line reached")
            //deadline reached exiting now
            exitProcess(1)
        }
        Thread.sleep(eachTimeDelay)
        firstLoop = false
    }
}

private fun defaultApp(
    appArguments: AppArguments,
    singleInstance: SingleInstanceUtil,
) {
    val singleInstanceServerHandler by lazy { MutableSingleInstanceServerHandler() }
    try {
        singleInstance.lockInstance { singleInstanceServerHandler }
    } catch (e: AnotherInstanceIsRunning) {
        println("instance already running")
        singleInstance.sendToInstance(Commands.showUserThatAppIsRunning)
        return
    }
    val startedMessage = "${AppInfo.displayName}-${AppInfo.version} started"
    appLogger.i { startedMessage }
    println(startedMessage)
    if (AppInfo.isInIDE()) {
        appLogger.i { "App is in IDE" }
    }

    val globalExceptionHandler = createAndSetGlobalExceptionHandler()
    App().use {
        it.start(
            appArguments = appArguments,
            globalAppExceptionHandler = globalExceptionHandler,
            singleInstanceServerHandler = singleInstanceServerHandler,
        )
    }
}
